---
apiVersion: v1
kind: ConfigMap
metadata:
  name: static-files
data:
  index2.html: |
    <html><head><title>End of the Internet</title></head>
    <body><h1>The End of the Internet</h1>
    <p>Karim2 is karim2 yeah.</p>
    </body></html>

  index3.html: |
    <html><head><title>End of the Internet</title></head>
    <body><h1>The End of the Internet</h1>
    <p>Karim3 is karim3 yeah.</p>
    </body></html>

  #index.html: |
  #  <html><head><title>End of the Internet</title></head>
  #  <body><h1>The End of the Internet</h1>
  #  <p>Karim is karim yeah.</p>
  #  </body></html>

   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: static-files
            mountPath: /usr/share/nginx/html
      volumes:
      - name: static-files
        configMap:
          name: static-files


---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service 
spec:
  type: LoadBalancer 
  ports:
  - port: 9000 
    name: my-nginx 
    targetPort: 80 
    protocol: TCP
  selector:
    app: test
  externalIPs:
  - 51.254.36.120
