apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-steps-templates-parallel
spec: 
  entrypoint: step-template-parallel
  templates:
  - name:  step-template-parallel
    steps:
    - - name: step1
        template: task-template
    - - name: step2
        template: task-template
      - name: step3
        template: task-template
    - - name: step4
        template: task-template

  - name:  task-template
    script: 
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task executed.")