kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1-pod-reader-binding
  namespace: testqa
subjects:
- kind: ServiceAccount
  name: user1
  namespace: testqa
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
