apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: exercice1
spec: 
  entrypoint: exercice1
  templates:
  - name:  exercice1
    dag:
      tasks:
      - name: TaskA
        template: taska-template
      - name: TaskB1
        template: taskb-template
        dependencies: [TaskA]
      - name: TaskB2
        template: taskb-template
        dependencies: [TaskB1]
      - name: TaskB3
        template: taskb-template
        dependencies: [TaskB2]
      - name: TaskC
        template: taskc-template
        dependencies: [TaskA]
      - name: TaskD
        template: taskd-template
        dependencies: [TaskB3, TaskC]

      - name: TaskA2
        template: taska-template
        dependencies: [TaskD]

  - name:  taska-template
    script: 
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task A executed successfully with script templates")

  - name: taskb-template
    container: 
      image: python:3.8-slim
      command : [echo ,  "Task B executed successfully with container templates."]

  - name: taskc-template
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          name: wf-test2
        spec:
          entrypoint: test2-template
          templates:
          - name: test2-template
            script: 
              image: python:3.8-slim
              command: [python]
              source: |
                print("Task C executed successfully with resource templates.")

  - name: taskd-template
    suspend:
      duration: "5s"