apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-sync-app-prune
  namespace: argocd
spec:
  destination: 
    namespace: auto-sync-app-prune
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: guestbook-with-sub-directories
    repoURL: git@github.com:kagzouli/testArgoCD.git
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
    - CreateNamespace=true
   