apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    name: my-nginx
    targetPort: 80
    protocol: TCP
  selector:
    app: test
  externalIPs:
  - 51.254.36.120

