apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app:  test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: static-files
            mountPath: /usr/share/nginx/html
      volumes:
      - name: static-files
        configMap:
          name: static-files
